### ISSUE TITLE
starting container process caused "exec: \"/usr/local/bin/twistd -n irrd\": stat /usr/local/bin/twistd -n irrd: no such file or directory": unknown.

### ISSUE THREAD

**Issue by ozkanpakdil** [mirceaulinic/docker-irrd#1]
I am trying to run irrd container in my laptop just to see how irrd works.

`user@laptop:~/docker-irrd$ sudo docker run --rm -d -v /etc/irrd.yaml mirceaulinic/irrd:4.0.8
Unable to find image 'mirceaulinic/irrd:4.0.8' locally
4.0.8: Pulling from mirceaulinic/irrd
Digest: sha256:e345e3289c30b8d608d2a15bb06ea7e9bae4c98eb5bb97fdedfc4e932d077b9f
Status: Downloaded newer image for mirceaulinic/irrd:4.0.8
e597194a9bbe3a5246e209c15711001ca8703a42f0335aecfd9e83310e801340
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/twistd -n irrd\": stat /usr/local/bin/twistd -n irrd: no such file or directory": unknown.
user@laptop:~/docker-irrd$ sudo docker run --rm -d -v /etc/irrd.yaml mirceaulinic/irrd
9835f261853fa53278dc3950f3ca50e17021f45efae8ab36e728f3f87ee2a7d7
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/twistd -n irrd\": stat /usr/local/bin/twistd -n irrd: no such file or directory": unknown.
`

any ideas ?

**Comment by lamehost** [comment]
To change CMD to: `CMD ["/usr/local/bin/twistd", "-n", "irrd"]` worked for me.
